output   = "web-service-gin/db/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "go-demo"
  host   = "postgresql"
  port   = 5432
  user   = "go-demo"
  pass   = "password"
  sslmode = "disable"
  blacklist = ["gorp_migrations"]